parameters:
  app.mock_network_data: '%env(bool:MOCK_NETWORK_DATA)%'
  app.favicon_provider: '%env(FAVICON_PROVIDER)%'
  app.local_subnets: '%env(LOCAL_SUBNETS)%'
  app.own_wan_ips: '%env(OWN_WAN_IPS)%'
  app.mikrotik_monitor_interface: '%env(default:ether1:MIKROTIK_MONITOR_INTERFACE)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      bool $mockNetworkData: '%app.mock_network_data%'
      string $faviconProvider: '%app.favicon_provider%'
      string $localSubnets: '%app.local_subnets%'
      string $ownWanIps: '%app.own_wan_ips%'
      string $mikrotikMonitorInterface: '%app.mikrotik_monitor_interface%'

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
